version: "3.6"

services:
  

    web: 
        container_name: webRLDD
        build:
            context: ./web/.
            dockerfile: Dockerfile
        ports:
            - "2023:80"
        networks: 
            - RLDD

    flask:
        container_name: model
        build : 
            context: ./model/.
            dockerfile: Dockerfile
        ports:
            - 5000:5000
networks: 
    RLDD:
